### ISSUE TITLE
Error specifying input file

### ISSUE THREAD

**Issue by grst** [icbi-lab/quanTIseq#1]
I am having trouble running the quanTIseq pipeline. 

When I try to run the pipeline using the provided example file, I get the error message `Please specify input files as described in the quanTIseq documentation`

```
>bash quanTIseq_pipeline.sh --inputfile="quanTIseqTest_input.txt"
ERROR: please specify input files as described in quanTIseq documentation. To inspect this image call: docker run -it --entrypoint=/bin/bash icbi/quantiseq
```

My file structure is available in [this repository](https://github.com/grst/running_quantiseq), the excact commands I executed are documented in [this notebook](https://github.com/grst/running_quantiseq/blob/master/running_quantiseq.ipynb).

Cheers, 
Gregor

**Comment by grst** [comment]
I figured it out. The issue was related to “SELinux” (Security Enhanced) which we use on our server. 
The solution was to add the “:z” flag to every mount command in docker as described on stackoverflow: 
https://stackoverflow.com/a/31334443/2340703
 
I suggest adding that to the quantiseq source, as SElinux is a quite common extension on linux servers.

**Comment by FFinotello** [comment]
Hi Gregor,

thanks for your feedback. We will keep this into consideration for the next releases.

Best,
Francesca
