### ISSUE TITLE
Discarding subset for deconvolution

### ISSUE THREAD

**Issue by SaTu84** [icbi-lab/quanTIseq#11]
Hi,

I am interested in running quanTIseq on whole blood data but I am running into the problem that Neutrophils are highly abundant and therefore it obscures the deconvolution results I obtain. Therefore I was trying to neglect Neutrophils on two ways:

- Filter the expression dataset to exclude genes specific to neutrophils.
- Adding those Neutrophil-specific genes to a txt file aiding to remove those genes during the deconvolution pipeline (rmgenes option).

Now, with both approaches I run into problems. With approach one I still seem to get samples with significant proportions of Neutrophils even though the genes deconvoluting this cell type are removed. With approach two I receive the following error: 

_Starting quanTIseq pipeline with Singularity

Running quanTIseq deconvolution module

Gene expression normalization and re-annotation (arrays: FALSE)

Error in file(file, "rt") : cannot open the connection
Calls: as.vector -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/opt/quantiseq/deconvolution//TIL10rmgenes.txt': No such file or directory
Execution halted_

I guess my question is whether there is a way to neglect neutrophils for deconvolution? Thanks in advance!

**Comment by FFinotello** [comment]
Hello @SaTu84 ,

thanks for reaching out.

Could you please share with us your file with gene names? @chripla and I will try to reproduce your error to check whether there is a bug in the code.

Nevertheless, I would suggest you not to remove the genes a priori, as this information is very helpful to disentangle the cellular sources of the expression "signal" found in the mixture, especially if these cell types that are known to be present in your sample. I would rather disregard a posteriori (i.e. after deconvolution) only the cell fractions that are not relevant to the analysis.

I hope this helps,
Francesca

**Comment by SaTu84** [comment]
Hi @FFinotello ,

Thank you for the fast reply. Please find the file attached. I also included the gene present in the "default" file for rmgenes.
[Neutr_Genes_Removed_For_DeconV.txt](https://github.com/icbi-lab/quanTIseq/files/6598153/Neutr_Genes_Removed_For_DeconV.txt)

With regard to your second remark: I understand that but the problem is that if I keep Neutrophils included for analysis, the relative abundance is calculated and since they are so highly present it will diminish the relative contribution of the other subsets as a consequence. Or am I misinterpreting things here?

Thank you!

**Comment by FFinotello** [comment]
Hello,

Thank you for sending the file. We will test it in the next few days.

As for your question, if neutrophils (truly) make up 70% of your mixture, for instance, the remaining cell types can only account altogethers for the remaining 30%. 
If you remove the neutrophils genes from your signature, there are two main problems.

First, quanTIseq will anyway try to estimate them as they are reported in one of the columns of the TIL10 signature matrix;

Second, large part of the RNA-seq signal in your sample (~70% in the example above, not accounting for mRNA biases for simplicity) would still come from them. So, if one imagine to remove the neutrophil-gene rows (possible) and neutrophil column (not possible) from the TIL10 signature matrix, still quanTIseq would try account for this signal and likely assign it to the fractions of "other" uncharacterized cells. 

So, the problem would remain and you would make just the deconvolution problem more complex.

If you are interested only in the PBMC fractions, you could remove the neutrophil (or neutrophil + other) cell fractions from your final estimates and normalize their their sum to 1 (= 100%).

So, if `X_cs `is the fraction of cell type `c` in sample `s`, I would normalize it as: `X_cs =  X_cs / X_s` , where `X_s` is the sum of all cell fractions in sample `s` after removal of your unwanted cell types.

Does this help?

Best,
Francesca

**Comment by SaTu84** [comment]
Thank you once again for elaborating on the matter. 

What you say makes sense. However, I have one remaining question (partially) based on the second point you made. The first approach I tried was to remove the neutrophil-gene rows from the expression data frame (to mimic them not to be expressed). Nevertheless, still for some samples neutrophil estimates were made (some being more 50%). How is this possible when I discard most signal coming from the neutrophils?

In any case, I will proceed as you suggested as this makes the most sense to do indeed. Just for the sake of my interest, please let me know what comes out of the test you will do with the rmgenes.txt.

Greetings!

**Comment by FFinotello** [comment]
I believe it could be due to some genes that have a non-negligible expression in neutrophils and were not excluded in your analysis, like SQOR and CLEC4A.

We will get back to you soon regarding the error.

Cheers,
Francesca

**Comment by chripla** [comment]
Hi @SaTu84, 

I checked the file and the error you have send us and it turned out that the file names got mixed up with mounting external files. Thanks for letting us know. The bug is fixed and it should work now.

Cheers,
Christina

**Comment by SaTu84** [comment]
Dear Christina,

Thank you so much for letting me know, good that is has been resolved!

Cheers
